### ISSUE TITLE
"yarn res link" command has been failed

### ISSUE THREAD

**Issue by sym233** [reason-seoul/yarn-plugin-rescript#14]
reproduce:
```
mkdir proj
cd proj
yarn init -2
yarn
yarn plugin import https://github.com/reason-seoul/yarn-plugin-rescript/releases/download/v0.0.0-da87589/plugin-rescript.js
yarn res init --module=es6
```
output:
```
➤ YN0000: Installing latest version of "rescript"
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ rescript@npm:9.1.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0s 387ms
➤ YN0000: ┌ Link step
➤ YN0007: │ rescript@npm:9.1.4 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 5s 626ms
➤ YN0000: Done in 6s 47ms
➤ YN0000: Config file generated at bsconfig.json

➤ YN0000: Done in 0s 17ms
Internal Error: EPERM: operation not permitted, symlink '[proj]\.yarn\unplugged\rescript-npm-9.1.4-75c65d01e7\node_modules\rescript' -> '[proj]\node_modules\rescript'
Error: EPERM: operation not permitted, symlink '[proj]\.yarn\unplugged\rescript-npm-9.1.4-75c65d01e7\node_modules\rescript' -> '[proj]\node_modules\rescript'
Internal Error: "yarn res link" command has been failed
    at k.tryCli ([proj]\.yarn\plugins\@yarnpkg\plugin-rescript.cjs:5:30191)
    at async k.execute ([proj]\.yarn\plugins\@yarnpkg\plugin-rescript.cjs:5:30032)
    at async k.validateAndExecute ([proj]\.yarn\releases\yarn-3.2.2.cjs:345:673)
    at async ws.run ([proj]\.yarn\releases\yarn-3.2.2.cjs:359:2087)
    at async ws.runExit ([proj]\.yarn\releases\yarn-3.2.2.cjs:359:2271)
    at async i ([proj]\.yarn\releases\yarn-3.2.2.cjs:446:12696)
    at async t ([proj]\.yarn\releases\yarn-3.2.2.cjs:446:10914)
```

os: win10 x64
node: 16.16.0

yarn: 3.2.2

**Comment by chriswilty** [comment]
Same problem here. Why is this plugin symlinking stuff into node_modules when I'm using Zero-Installs, is it a workaround? Looks like it's setting rescript as unplugged; would I also need to commit node_modules in that case?

In any case, that'll likely only work on linux machines.
